module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src/'],
  testRegex: '.*\\.(spec|e2e-spec)\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: './coverage',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/src/core/infrastructure/auth',
    '/src/core/infrastructure/db',
    '/src/core/infrastructure/di',
    '/src/migrations/',
    '/src/entities/',
    '/src/errors/',
    '/src/lib/validators/',
    '/src/index.ts',
    '/src/test/',
    '/src/.*index\\.ts$',
    'typeorm.config.ts',
  ],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  setupFilesAfterEnv: ['./jest.setup.ts'],
  moduleNameMapper: {
    '^@infra$': '<rootDir>/src/core/infrastructure',
    '^@infra/(.*)$': '<rootDir>/src/core/infrastructure/$1',
    '^@http$': '<rootDir>/src/core/infrastructure/http/adapters/inversifyAdapter',
    '^@http/(.*)$': '<rootDir>/src/core/infrastructure/http/adapters/$1',
    '^@lib$': '<rootDir>/src/lib',
    '^@lib/(.*)$': '<rootDir>/src/lib/$1',
    '^@entities$': '<rootDir>/src/entities',
    '^@entities/(.*)$': '<rootDir>/src/entities/$1',
    '^@repositories$': '<rootDir>/src/repositories',
    '^@repositories/(.*)$': '<rootDir>/src/repositories/$1',
    '^@services$': '<rootDir>/src/services',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@controllers$': '<rootDir>/src/controllers',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@dtos$': '<rootDir>/src/dtos',
    '^@dtos/(.*)$': '<rootDir>/src/dtos/$1',
    '^@errors$': '<rootDir>/src/errors',
    '^@errors/(.*)$': '<rootDir>/src/errors/$1',
    '^@routes$': '<rootDir>/src/routes',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
  },
};
